server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: bms-api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: bms-employee-service
          uri: lb://bms-employee-service
          predicates:
            - Path=/employee/**
        - id: bms-reservation-service
          uri: lb://bms-reservation-service
          predicates:
            - Path=/reservation/**
        - id: bms-reports-service
          uri: lb://bms-reports-service
          predicates:
            - Path=/reports/**  
        - id: bms-department-service
          uri: lb://bms-department-service
          predicates:
            - Path=/department/**
